### ISSUE TITLE
Installing Docker for app

### ISSUE THREAD

**Issue by rogersentongo** [diegomais/gobarber#1]
Hi,
Could you please provide some guidance for using docker to setup a database.

**Comment by diegomais** [comment]
Hi,
I updated the instructions in README:

Install [Docker Desktop](https://www.docker.com/get-started).
Start a PostgreSQL instance: `docker run --name gobarber-pg -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -d postgres`
Start a MongoDB instance: `docker run --name gobarber-mongo -p 27017:27107 -d mongo`
Start a Redis instance: `docker run --name gobarber-redis -p 6379:6379 -d redis`

**Comment by rogersentongo** [comment]
Thank you, let me try that and get back to you asap.
